### ISSUE TITLE
InvalidOperationException in v2018.1.0b8 (and how to fix it!)

### ISSUE THREAD

**Issue by antoinefournier** [LotteMakesStuff/SimplePhysicsDemo#3] opened 2018-02-23 21:29 UTC
First of all thank you for giving us this little demo :)
I tried it today with the latest beta version 2018.1.0b8 and this error shows up at runtime:

`InvalidOperationException: The previously scheduled job SimpleJobifiedPhysics:PrepareRaycastCommands writes to the NativeArray PrepareRaycastCommands.Raycasts. You must call JobHandle.Complete() on the job SimpleJobifiedPhysics:PrepareRaycastCommands, before you can write to the NativeArray safely.
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckWriteAndThrowNoEarlyOut (AtomicSafetyHandle handle)
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckWriteAndThrow (AtomicSafetyHandle handle) (at C:/buildslave/unity/build/Runtime/Export/AtomicSafetyHandle.bindings.cs:155)
Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafePtr[RaycastCommand] (NativeArray`1 nativeArray) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:353)
UnityEngine.RaycastCommand.ScheduleBatch (NativeArray`1 commands, NativeArray`1 results, Int32 minCommandsPerJob, JobHandle dependsOn) (at C:/buildslave/unity/build/Runtime/Dynamics/ScriptBindings/RaycastCommand.bindings.cs:35)
SimpleJobifiedPhysics.Update () (at Assets/SimpleJobifiedPhysics.cs:237)
`

The `setupRaycastsJob` need to be completed, l.237:
`var setupDependency = setupRaycastsJob.Schedule(objectCount, 32, gravityDependency);
setupDependency.Complete();`

**Comment by LotteMakesStuff** [comment] 2018-02-23 23:25
This is a duplicate of Issue #2, which has been fixed with the same temporary workaround as you presented here. This is actually a bug in RaycastCommand, its ignoring passed in dependencies. This has been fixed by Unity but i dont know when that bugfix will hit the public beta

**Closed as completed** 2018-02-24 00:02 UTC
